#%RAML 1.0
title: customer phone number verify API

uses:
  myLib: library.raml

/validatePhoneNumber:
  displayName: validate Customer Phone Number
  description: Customer Phone Number
  get:
    displayName: GEt Verified Customer Phone Number
    description: Returns validated Data if a customer phone number is verified
    queryParameters:
      phoneNumber:
        displayName: Phone
        description: Customr Phone Used to Verify members
        type: string
        pattern: "[0-9|-]+"
        
    responses:
      200:
        body:
          application/json:
            type: myLib.dataTypes
            example: !include example.raml
    is:
      - myLib.errorResp
      - myLib.mysec




               
   

